//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfTransactionClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Zlecenie_glosowania", ReplyAction="http://tempuri.org/IService1/Zlecenie_glosowaniaResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        bool Zlecenie_glosowania();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Zlecenie_glosowania", ReplyAction="http://tempuri.org/IService1/Zlecenie_glosowaniaResponse")]
        System.Threading.Tasks.Task<bool> Zlecenie_glosowaniaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Zatwierdzanie_globalne", ReplyAction="http://tempuri.org/IService1/Zatwierdzanie_globalneResponse")]
        bool Zatwierdzanie_globalne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Zatwierdzanie_globalne", ReplyAction="http://tempuri.org/IService1/Zatwierdzanie_globalneResponse")]
        System.Threading.Tasks.Task<bool> Zatwierdzanie_globalneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Zaniechanie_globalne", ReplyAction="http://tempuri.org/IService1/Zaniechanie_globalneResponse")]
        bool Zaniechanie_globalne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Zaniechanie_globalne", ReplyAction="http://tempuri.org/IService1/Zaniechanie_globalneResponse")]
        System.Threading.Tasks.Task<bool> Zaniechanie_globalneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfTransactionClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfTransactionClient.ServiceReference1.IService1>, WcfTransactionClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Zlecenie_glosowania() {
            return base.Channel.Zlecenie_glosowania();
        }
        
        public System.Threading.Tasks.Task<bool> Zlecenie_glosowaniaAsync() {
            return base.Channel.Zlecenie_glosowaniaAsync();
        }
        
        public bool Zatwierdzanie_globalne() {
            return base.Channel.Zatwierdzanie_globalne();
        }
        
        public System.Threading.Tasks.Task<bool> Zatwierdzanie_globalneAsync() {
            return base.Channel.Zatwierdzanie_globalneAsync();
        }
        
        public bool Zaniechanie_globalne() {
            return base.Channel.Zaniechanie_globalne();
        }
        
        public System.Threading.Tasks.Task<bool> Zaniechanie_globalneAsync() {
            return base.Channel.Zaniechanie_globalneAsync();
        }
    }
}
